### ISSUE TITLE
Meele attack icon getting stuck on screen untill you do/get dmg no text shown

### ISSUE THREAD

**Issue by Tonyleila** [dandruff/xCT#101]
Its just stuck there untill something else scrolls it away. I had it like this for 10 mins outfight. I made an /fstack screenshot in case that helps but I guess no.
http://imgur.com/a/4Jl0M

edit: other spells incomming also show this.

**Comment by Cimplex** [comment]
Ya, sadly this is a known blizzard issue. It seems to crop up more when custom fade animations are enabled (just using those functions seem to cause it). Enabling "Clear Frames" (on the third line when you open the config) can mitigate most of it.

**Comment by Xruptor** [comment]
Using /reloadui or /reload also works too if you
