### ISSUE TITLE
Feature Request - Filter: Incoming Spells

### ISSUE THREAD

**Issue by behub-au** [dandruff/xCT#104]
Please add this. There seems to be no merging on incoming damage (spells) so i need a way to just hide the spam from stagger.

**Comment by Xruptor** [comment]
I had made a similar request on Curse a long time ago.  The author responded to it and said he got enough requests that he would implement it.

https://mods.curse.com/addons/wow/xct-plus?comment=295

(copy and pasted)

Hey dandraffbal!
 
First off thanks for such a great addon.  Had been using a modified version of xCT that I edited myself for quite some time.  Yours on the other hand is MUCH better and flexible then mine ever was lol :D
 
On that note, do you think you could add filtering for incoming as well?  Example, on my Warlock I really don't need to see incoming heals for Soul Link based on the Fel Armor talent I have enabled.  Would be nice to be able to filter some stuff out in the Incoming frame as well.  I tried using the Buffs filtering but that applies to a different frame altogether.
 
Thanks again!

**Comment by Cimplex** [comment]
Should be easy enough to implement now that I have the new parser working. Will update in a bit.
