### ISSUE TITLE
7.1 error

### ISSUE THREAD

**Issue by Moogoose** [dandruff/xCT#108]
Message: LibPlayerSpells-1.0: 4 errors in HUNTER database: 
Data are probably outdated: data version=70000, client version=70100 
Spell #204333: unknown spell 
Spell #204324: unknown spell 
Spell #204321: unknown spell 
Time: Fri Nov 4 12:41:54 2016 
Count: 1 
Stack: ...AddOns\xCT+\libs\LibPlayerSpells-1.0\data\Hunter.lua:23: in main chunk 

Locals: lib = { 
__modifiers = { 
} 
IterateSpells = defined @Interface\AddOns\xCT+\libs\LibPlayerSpells-1.0\LibPlayerSpells-1.0.lua:337 
__RegisterSpells = defined @Interface\AddOns\xCT+\libs\LibPlayerSpells-1.0\LibPlayerSpells-1.0.lua:478 
constants = { 
} 
GetDispelTypeNames = defined @Interface\AddOns\xCT+\libs\LibPlayerSpells-1.0\LibPlayerSpells-1.0.lua:382 
__categories = { 
} 
masks = { 
} 
GetCrowdControlTypes = defined @Interface\AddOns\xCT+\libs\LibPlayerSpells-1.0\LibPlayerSpells-1.0.lua:350 
GetCrowdControlCategoryName = defined @Interface\AddOns\xCT+\libs\LibPlayerSpells-1.0\LibPlayerSpells-1.0.lua:365 
__sources = { 
} 
GetSpellInfo = defined @Interface\AddOns\xCT+\libs\LibPlayerSpells-1.0\LibPlayerSpells-1.0.lua:403 
__versions = { 
} 
__specials = { 
} 
__filters = { 
} 
__spells = { 
} 
__providers = { 
} 
GetFlagTester = defined @Interface\AddOns\xCT+\libs\LibPlayerSpells-1.0\LibPlayerSpells-1.0.lua:289 
GetSpellTester = defined @Interface\AddOns\xCT+\libs\LibPlayerSpells-1.0\LibPlayerSpells-1.0.lua:319 
GetVersionInfo = defined @Interface\AddOns\xCT+\libs\LibPlayerSpells-1.0\LibPlayerSpells-1.0.lua:269 
GetDispelTypes = defined @Interface\AddOns\xCT+\libs\LibPlayerSpells-1.0\LibPlayerSpells-1.0.lua:356 
IterateCategories = defined @Interface\AddOns\xCT+\libs\LibPlayerSpells-1.0\LibPlayerSpells-1.0.lua:344 
}

**Comment by Cimplex** [comment]
The latest version is on Curse.
