### ISSUE TITLE
Incoming (Damage) won't justify left.

### ISSUE THREAD

**Issue by Xionyus** [dandruff/xCT#112]
I have Incoming (Damage) and Incoming (Healing) combined into the same window as shown here:
![](https://i.gyazo.com/6be9587299993eb773bfa992a5f56fed.png)

I have Incoming (Damage) set to Justification: Left and this is the result:
![](https://i.gyazo.com/4837bfd7bb595f43e30855fabf189488.png)

Incoming (Healing) is also set to Justification: Left:
![](https://i.gyazo.com/160dd14b3c0054e17b1a79e82ea6feee.png)

Result is Incoming (Damage) is justified to the right and Incoming (Healing) is justified to the left as intended:
![](https://i.gyazo.com/7f2c430e77eaba6b5a9e40ff1e3de041.png)

I've got UI OCD, so I'd appreciate it if you could fix it, or tell me what I'm doing wrong.

**Comment by Cimplex** [comment]
Looks like I am not showing an invisible icon when icons for healing are turned off. This will be fixed in the next version.

**Comment by behub** [comment]
That commit has resulted in this happening:
![image](https://cloud.githubusercontent.com/assets/870239/21577669/78e3e9a4-cfb7-11e6-904b-627d135bcdd6.png)

Unless i am wrong but it was the only change done between play sessions.

**Comment by dandruff** [comment]
Ugh. Good find. Reopening
