### ISSUE TITLE
LibPlayerSpells-1.0: 4 errors in HUNTER database

### ISSUE THREAD

**Issue by demanl** [dandruff/xCT#120]
Currently getting the following error upon logging into every character;

`Date: 2017-02-08 18:04:59
ID: 1
Error occured in: Global
Count: 1
Message: LibPlayerSpells-1.0: 4 errors in HUNTER database:
Data are probably outdated: data version=70000, client version=70100
Spell #204333: unknown spell
Spell #204324: unknown spell
Spell #204321: unknown spell
Debug:
   ...AddOns\xCT+\libs\LibPlayerSpells-1.0\data\Hunter.lua:23: in main chunk
Locals:
None
AddOns:
  Swatter, v7.3a.5701 (TasmanianThylacine)
  Altoholic, vr177
  AucAdvanced, v7.3a.5701 (TasmanianThylacine)
  AucFilterBasic, v7.3a.5701 (TasmanianThylacine)
  AucFilterOutlier, v7.3a.5701.5459(7.3a/embedded)
  AucMatchUndercut, v7.3a.5701.5585(7.3a/embedded)
  AucStatHistogram, v7.3a.5701 (TasmanianThylacine)
  AucStatiLevel, v7.3a.5701 (TasmanianThylacine)
  AucStatPurchased, v7.3a.5701 (TasmanianThylacine)
  AucStatSales, v7.3a.5701.5598(7.3a/embedded)
  AucStatSimple, v7.3a.5701 (TasmanianThylacine)
  AucStatStdDev, v7.3a.5701 (TasmanianThylacine)
  AucStatWOWEcon, v7.3a.5701.5613(7.3a/embedded)
  AucUtilAHWindowControl, v7.3a.5701.5575(7.3a/embedded)
  AucUtilAppraiser, v7.3a.5701.5666(7.3a/embedded)
  AucUtilAskPrice, v7.3a.5701.5599(7.3a/embedded)
  AucUtilAutoMagic, v7.3a.5701.5686(7.3a/embedded)
  AucUtilCompactUI, v7.3a.5701.5694(7.3a/embedded)
  AucUtilEasyBuyout, v7.3a.5701.5576(7.3a/embedded)
  AucUtilFixAH, v7.3a.5701 (TasmanianThylacine)
  AucUtilItemSuggest, v7.3a.5701.5651(7.3a/embedded)
  AucUtilPriceLevel, v7.3a.5701.5633(7.3a/embedded)
  AucUtilScanButton, v7.3a.5701.5631(7.3a/embedded)
  AucUtilScanFinish, v7.3a.5701.5588(7.3a/embedded)
  AucUtilScanProgress, v7.3a.5701.4979(7.3a/embedded)
  AucUtilScanStart, v7.3a.5701.5347(7.3a/embedded)
  AucUtilSearchUI, v7.3a.5701.5672(7.3a/embedded)
  AucUtilSimpleAuction, v7.3a.5701.5654(7.3a/embedded)
  AucUtilVendMarkup, v7.3a.5701.4828(7.3a/embedded)
  Babylonian, v5.1.DEV.332(/embedded)
  BeanCounter, v7.3a.5701 (TasmanianThylacine)
  Clique, vv70100-1.1.0-bec043c
  Configator, v5.1.DEV.406(/embedded)
  DataStore, vr61
  DataStoreAchievements, vr44
  DataStoreAgenda, vr24
  DataStoreAuctions, vr46
  DataStoreCharacters, vr37
  DataStoreContainers, vr54
  DataStoreCrafts, vr75
  DataStoreCurrencies, vr33
  DataStoreGarrisons, vr19
  DataStoreInventory, vr47
  DataStoreMails, vr47
  DataStorePets, vr40
  DataStoreQuests, vr39
  DataStoreReputations, vr38
  DataStoreSpells, vr28
  DataStoreStats, vr27
  DataStoreTalents, vr57
  DebugLib, v5.1.DEV.337(/embedded)
  ElvUI, v10.43
  ElvUICastBarOverlay, v1.05
  ElvUICodeNameBlaze, v1.61
  ElvUICustomTweaks, v1.31
  ElvUIEverySecondCounts, v1.18
  ElvUILocPlus, v2.22
  ElvUIVisualAuraTimers, v1.50
  HandyNotes, vv1.4.12
  HandyNotesDraenorTreasures, v1.20a
  HandyNotesLegionRaresTreasures, v1.01b
  LibExtraTip, v5.12.DEV.423(/embedded)
  LightHeaded, vv70100-1.1.0-2016-12-29-ddba7c1
  Recount, vv7.1.5a release
  Stubby, v7.3a.5701 (TasmanianThylacine)
  TinyPad, v2.1.3
  TipHelper, v5.12.DEV.405(/embedded)
  xCT, v4.3.0 Beta 5
  BlizRuntimeLib_enUS v7.1.5.70100 <none>
  (ck=a3f)`

**Comment by behub** [comment]
Interesting. LibPlayerSpells got removed from the addon back in October.
https://github.com/dandruff/xCT/commit/cb4e2d996078c3173d9524ccb1f9964207c0b8f4

**Comment by behub** [comment]
You're running an old version of xCT from what i can see. We're up to xCT+ 4.3.3 Beta 5, where you are running v4.3.0 Beta 5

**Comment by demanl** [comment]
Hi behub,
I was using the current version of xCT+ available on tukui.org elvui website....which is the v4.2.0 beta 5 version...my bad. Sorry.

I'm now using the version available from curseforge.com which is more current...:)

**Comment by Cimplex** [comment]
I'll try to keep tukui.org updated with at least the release versions, but I am never over there anymore.
