### ISSUE TITLE
Kill Command not displaying correctly for BM Hunter's

### ISSUE THREAD

**Issue by ghost** [dandruff/xCT#122]
Kill Command Damage doesn't show for pet's by default, even if you select to Allow Pet Crits.

To get this to show I need to use the whitelist under 'Outgoing Spells' and  turn on 'Allow Pet Crits' under 'Outgoing (Criticals)'.

At this point it only shows Hati's(artifact weapon pet) Kill Command, to get my main pet's damage to show I need to un-check 'Merge Pet Abilities' under 'Spam Merger'.

If I then choose to 'Merge Critical Hits with Outgoing' under 'Spam Merger' it won't merge them into the Outgoing Frame. It still separates the damage. I have also noticed this with other pet abilities.

**Comment by Cimplex** [comment]
Sorry for the silence. I've looked at this issue in the past and thought I had fixed something. I will look into again! Thanks for the report.
