### ISSUE TITLE
Combattext.lua error

### ISSUE THREAD

**Issue by geggiot** [dandruff/xCT#128]
> 33x xCT+\modules\combattext.lua:1298: script ran too long
xCT+\modules\combattext.lua:1298: in function `?'
xCT+\modules\combattext.lua:571: in function <xCT+\modules\combattext.lua:555>

Locals:
(*temporary) = <function> defined =[C]:-1
(*temporary) = 0
(*temporary) = "script ran too long"
x = <table> {
 SetDefaultModuleLibraries = <function> defined @!KalielsTracker\Libs\AceAddon-3.0\AceAddon-3.0.lua:398
 runeIcons = <table> {
 }
 UpdateComboPointOptions = <function> defined @xCT+\core.lua:754
 OnSpamUpdate = <function> defined @xCT+\modules\frames.lua:482
 CombatStateChanged = <function> defined @xCT+\core.lua:1575
 MigratePrint = <function> defined @xCT+\core.lua:241
 EnableModule = <function> defined @!KalielsTracker\Libs\AceAddon-3.0\AceAddon-3.0.lua:363
 RestoreAllDefaults = <function> defined @xCT+\modules\frames.lua:1083
 baseName = "xCT+"
 IterateEmbeds = <function> defined @!KalielsTracker\Libs\AceAddon-3.0\AceAddon-3.0.lua:473
 EndConfigMode = <function> defined @xCT+\modules\frames.lua:784
 Clear = <function> defined @xCT+\modules\frames.lua:261
 Printf = <function> defined @Accountant_Classic\Libs\AceConsole-3.0\AceConsole-3.0.lua:69
 CombatLogEvent = <function> defined @xCT+\modules\combattext.lua:2550
 SetDefaultModulePrototype = <function> defined @!KalielsTracker\Libs\AceAddon-3.0\AceAddon-3.0.lua:440
 AddSpamMessage = <function> defined @xCT+\modules\frames.lua:393
 defaultModuleState = true
 EndTestMode = <function> defined @xCT+\modules\frames.lua:1070
 GenerateColorOptions = <function> defined @xCT+\core.lua:1406
 DisableModule = <function> defined @!KalielsTracker\Libs\AceAddon-3.0\AceAddon-3.0.lua:381
 Abbreviate = <function> defined @xCT+\modules\frames.lua:286
 GetArgs = <function> defined @Accountant_Classic\Libs\AceConsole-3.0\AceConsole-3.0.lua:144
 spellCache = <table> {
 }
 FrameTitles = <table> {
 }
 LoadAlignmentGrid = <function> defined @xCT+\modules\grid.lua:23
 db = <table> {
 }
 ToggleConfigMode = <function> defined @xCT+\modules\frames.lua:855
 QuickClassFrameUpdate = <function> defined @xCT+\modules\combattext.lua:720
 SetEnabledState = <function> defined @!KalielsTracker\Libs\AceAddon-3.0\AceAddon-3.0.lua:455
 enabledState = true
 UpdateCombatTextEvents = <function> defined @xCT+\modules\combattext.lua:111
 EnableFrameScrolling = <function> defined @xCT+\modules\frames.lua:239
 OnCombatTextEvent = <function> defined @xCT+\modules\combattext.lua:555
 UpdatePlayer = <function> defined @xCT+\modules\combattext.lua:83
 IterateModules = <function> defined @!KalielsTracker\Libs\AceAddon-3.0\AceAddon-3.0.lua:468
 events = <table> {
 }
 UpdateSpamSpells = <function> defined @xCT+\core.lua:450
 UpdateItemTypes = <function> defined @xCT+\core.lua:607
 Enable = <function> defined @!KalielsTracker\Libs\AceAddon-3.0\AceAddon-3.0.lua:325
 NewModule = <function> defined @!KalielsTracker\Libs\AceAddon-3.0\AceAddon-3.0.lua:266
 ShowConfigTool = <function> defined @xCT+\core.lua:1706
 DisableFrameScrolling = <function> defined @xCT+\modules\frames.lua:246
 lowMana = false
 lowHealth = false
 OnAddonConfigRefreshed = <function> defined @xCT+\core.lua:1612
 defaultModuleLibraries = <table> {
 }
 LOADED_COMBO_POINTS_OPTIONS = true
 combatEvents = <unnamed> {
 }
 UnregisterChatCommand = <function> defined @Accountant_Classic\Libs\AceConsole-3.0\AceConsole-3.0.lua:111
 existingProfile = <table> {
 }
 cvar_update = <function> defined @xCT+\modules\options.lua:149
 TrackxCTCommand = <function> defined @xCT+\core.lua:1782
 HideConfigTool = <function> defined @xCT+\core.lua:1757
 lootUpdater = <unnamed> {
 }
 GetName = <function> defined @

>

**Comment by Cimplex** [comment]
Any more information about when this is happening? How often? Or any other details?
