### ISSUE TITLE
2 skill not merging

### ISSUE THREAD

**Issue by kerberos42** [dandruff/xCT#136]
Hi.
I notice two skill no merging in the outgoing so far.

1) Entropic Embrace (ID 256374 and ID 259756)
2) Mind Flay (ID 237388)

Gread addon btw, I hope you can add them.

Thank you.

**Comment by pjgiemza** [comment]
Yeah, merge is an issue. I hope he can provide custom merge options so we can actually take load off him and make those ourselves.
