### ISSUE TITLE
Xct+ Error loading Interface

### ISSUE THREAD

**Issue by tresrottn** [dandruff/xCT#141]
I'm surprised no one is reporting this. My Xct+ is completely non-functional. This is the error I am getting. 
First is this one, 
Message: Error loading Interface\AddOns\xCT+\modules\messages.lua
Time: Thu Jul 19 13:54:58 2018
Count: 4

Then this longer one. 

2x xCT+\modules\combattext.lua:124: Attempt to register unknown event "UNIT_POWER"
[C]: in function `RegisterEvent'
xCT+\modules\combattext.lua:124: in function `UpdateCombatTextEvents'
xCT+\core.lua:124: in function <xCT+\core.lua:85>
(tail call): ?
[C]: ?
[string "safecall Dispatcher[1]"]:9: in function <[string "safecall Dispatcher[1]"]:5>
(tail call): ?
Ace3\AceAddon-3.0\AceAddon-3.0-12.lua:529: in function `InitializeAddon'
Ace3\AceAddon-3.0\AceAddon-3.0-12.lua:644: in function <Ace3\AceAddon-3.0\AceAddon-3.0.lua:636>

Locals:
nil

Now, I noticed "Ace3" being mentioned in this, so I disabled it, and reloaded and got the same error. 
I disabled ALL the addons except for Xct+ and I get this error

Message: Error loading Interface\AddOns\xCT+\modules\messages.lua
Time: Thu Jul 19 14:02:50 2018
Count: 5

With the same LUA error 
4x xCT+\modules\combattext.lua:124: Attempt to register unknown event "UNIT_POWER"
[C]: in function `RegisterEvent'
xCT+\modules\combattext.lua:124: in function `UpdateCombatTextEvents'
xCT+\core.lua:124: in function <xCT+\core.lua:85>
(tail call): ?
[C]: ?
[string "safecall Dispatcher[1]"]:9: in function <[string "safecall Dispatcher[1]"]:5>
(tail call): ?
Ace3\AceAddon-3.0\AceAddon-3.0-12.lua:529: in function `InitializeAddon'
Ace3\AceAddon-3.0\AceAddon-3.0-12.lua:644: in function <Ace3\AceAddon-3.0\AceAddon-3.0.lua:636>

Locals:
nil

Thanks!

**Comment by Toludin** [comment]
Looks like you don't have the latest version of the addon. I removed the reference to messages.lua (a non-existent file) a few updates ago, and your error on line 124 of combattext.lua is from an old build. The current build's line 124 is:

x.player.class  = select(2, UnitClass("player"))

That line before the BfA update was:

f:RegisterEvent("UNIT_POWER")

UNIT_POWER is no longer an event (replaced by UNIT_POWER_UPDATE), hence why it's throwing an error.

I'd recommend fully deleting your xCT+ folder from your addons directory and reinstalling. If the Twitch client isn't doing it right, you can download from here directory with the "Clone or download" button on the main page of the repository (choose "Download ZIP" from that drop-down).

Hope that helps!

**Comment by tresrottn** [comment]
Oh yah, for sure, Twitch/Curse app is pushing out v4.3.2 instead of your updated version. Might want to yell at them, lol. 
I'ma dl the 4.4.0 now, and thank you so very much for the quick response!

**Comment by Toludin** [comment]
Sure thing! Going to close this one out.
