### ISSUE TITLE
Spell icon

### ISSUE THREAD

**Issue by 1ps3** [dandruff/xCT#142]
Change spell icons from an escape sequence to a texture, so it can be skinned by other addons.

**Comment by Cimplex** [comment]
I'll look into it, but it would require a significant change to how I use message scrolling frames. I don't think there is a way of attaching textured frames to a ScrollingMessageFrame at this time, which is why I've used an escape sequence this whole time.

**Comment by RedAces** [comment]
Not planned atm, but Im open for pull requests.
