### ISSUE TITLE
Customizable merge class spells

### ISSUE THREAD

**Issue by aranval** [dandruff/xCT#147]
As a rogue I have huge issues with damage spells and buffs spamming. Rupture on multiple targets, Poison Bomb talent proc, buffs such as Overwhelming Power or Sharpened Blades. Possibly more, those were just of top of my head.
*was meant to be feature request*
Add to that Creeping Venom spam (PvP talent poison). There are tons of things that youd have to include manually.

**Comment by pjgiemza** [comment]
*was meant to be feature request*

**Comment by pjgiemza** [comment]
Add to that Creeping Venom spam (PvP talent poison). There are tons of things that youd have to include manually.
