### ISSUE TITLE
Feature Request: Spell School / colors

### ISSUE THREAD

**Issue by Homaxz** [dandruff/xCT#152]
I would like to request customisable spell school colors for interrupts. For example:

Have an option that shows the spell school instead of the cast name.
If I interrupt 'Mind Flay' from a priest, then it says: Interrupted 'shadow' instead. Along with customisable colors for each school. Although preset colors for each school would work as well.

**Comment by RedAces** [comment]
Not planned atm, but Im open for Merge Requests.
