### ISSUE TITLE
[Question] Frame Animations

### ISSUE THREAD

**Issue by Imiona** [dandruff/xCT#158]
Hello

I would like to ask if there will ever be more Frame Animations (like in MSBT or Parrot), right now, there is only static. Its the only Thing that keeps me from using your Adddon, the rest is really well done.

**Comment by Imiona** [comment]
Bump 2 Years later :)

**Comment by Imiona** [comment]
Bump again 1 Year later :)

**Comment by RedAces** [comment]
Nothing planned atm but Im to pull requests :)
