### ISSUE TITLE
Blizzards' incoming heals & damage still showing 

### ISSUE THREAD

**Issue by aidenlangley** [dandruff/xCT#168]
Hey Dandruff 👍 

Might remember me as Asi from Tukui but haven't been active for a long, long time. Just got back into WoW.

So pretty much just using ElvUI, xCT+, and Skada here. I leave the default combat numbers for outbound damage, but use xCT+ for incoming heals/damage, combat notifications and currency income. Settings that I thought would be relevant are below.

Problem is I'm still seeing Blizzards default SCT too - incoming damage and heals.

Appreciate the work you do.

![Screenshot_6](https://user-images.githubusercontent.com/684721/97380649-5f1e2a80-192c-11eb-9690-9c4c0450cedc.png)
![Screenshot_5](https://user-images.githubusercontent.com/684721/97380468-f6cf4900-192b-11eb-9cd1-7351e9f13383.png)
![Screenshot_4](https://user-images.githubusercontent.com/684721/97380472-fafb6680-192b-11eb-828c-52ba25cf76fb.png)
![Screenshot_3](https://user-images.githubusercontent.com/684721/97380476-fdf65700-192b-11eb-98cf-791cced6d2d8.png)
![Screenshot_2](https://user-images.githubusercontent.com/684721/97380478-ff278400-192b-11eb-992e-f137ee60fdfe.png)

**Comment by Cimplex** [comment]
Sorry it took so long to get back to you. That last picture, uncheck "Enable Scrolling Combat Text (Self)". I think is what you want
