### ISSUE TITLE
bug with icons

### ISSUE THREAD

**Issue by SumsarTheThird** [dandruff/xCT#170]
i have this issue, where even though i disable icons, there is still space left for them, messing with the allignment of the numbers. 

there is 3 pictures here, to better illustrate the problem. 
pic 1: testmode: shown correctly, although its also still showing name there, even though that is also disabled.
https://drive.google.com/file/d/1pNeL01MXJsqermN94_aCZnvDaRB-4NfI/view?usp=sharing
pic 2: with icons: 
https://drive.google.com/file/d/1uMOM860qEgZBUJQYVxHAuu6c6XwJrpbS/view?usp=sharing
pic 3: Without icons
https://drive.google.com/file/d/153LCmJhSDzRHQpvbqN6CQUcRCRYEncba/view?usp=sharing

Would be absolutely magnificent if this could get fixed. your addon is perfection otherwise! keep it up!

**Comment by Cimplex** [comment]
Adding a new option to hide invisible "spacer" icons when Icons are disabled:
![hide invisible icons](https://user-images.githubusercontent.com/664988/102684034-d0df5b80-419a-11eb-847f-c63b9f2139f3.png)

**Comment by SumsarTheThird** [comment]
As far as i can tell, after running a mythic +, your toggle seems to be fixing it. 
for reference, here is a picture of how it looks after your fix:
https://drive.google.com/file/d/1nuSaSGC4VGtJwZjMj_L81vRVjsV7IOHO/view?usp=sharing
