### ISSUE TITLE
Sometimes i get this error

### ISSUE THREAD

**Issue by voidlol** [dandruff/xCT#171]
3x xCT+\modules\combattext.lua:579: bad argument #3 to 'sformat' (string expected, got function)
[string "=[C]"]: ?
[string "@xCT+\modules\combattext.lua"]:579: in function `GetSpellTextureFormatted'
[string "@xCT+\modules\combattext.lua"]:1684: in function `OutgoingMiss'
[string "@xCT+\modules\combattext.lua"]:1861: in function `func'
[string "@xCT+\libs\xCombatParser-1.0\xCombatParser-1.0-1.lua"]:398: in function <...ns\xCT+\libs\xCombatParser-1.0\xCombatParser-1.0.lua:199>

Locals:
(*temporary) = "%s %s"
(*temporary) = " |T3509650:14:14:0:0:64:64:5:59:5:59|t"
(*temporary) = <function> defined @SharedXML\SharedBasicControls.lua:19
(*temporary) = "string expected, got function"

**Comment by Cimplex** [comment]
Do you know what version you are using? What's weird is the line numbers indicate that this should be happening when you interrupt someone, but the call stack is saying it is when you have a miss. So the version is needed.

**Comment by voidlol** [comment]
Version 4.4.8

**Comment by Cimplex** [comment]
If you update to the latest version (4.5.2), do you still get the error? You can also use Curse client to auto update:

https://www.curseforge.com/wow/addons/xct-plus/files/3132806
