### ISSUE TITLE
Fixed for TBC Classic but getting gui error.. please help!

### ISSUE THREAD

**Issue by JFre3** [dandruff/xCT#180]
Hello, I am an old school wow player that used xct back in the day due to the lightweight mem/cpu usage and when I came back for classic wow, it was my go to scrolling combat text! A user posted a link to a working version for classic on the curseforged page and I used it fine for the whole classic. When TBC prepatch was released, it unfortunately broke xct so I then went to get the latest version xCT+4.5.3(9.0.2) - Beta 5 and started applying the changes that I found in the fixed classic files. I was then able to edit out a few more things and got it working fine with no errors. The only issue I encountered was the gui is broken and below is the error I am receiving :(  

xct is working fine with my old saved variables but I would like to setup some new stuff on new toons, so I tried editing the savedvar file manually and ran into issue. If maybe you can help fix the gui by removing the new characters/races from it as that is what most of the old fix was. Thank you for supporting such a great add-on for so many years.. cheers!

3x ...nfig-3.0\AceConfigDialog-3.0\AceConfigDialog-3.0-81.lua:445: AceConfigRegistry-3.0-20:ValidateOptionsTable(): xCT+.args.spells.args.classList.args.DEATHKNIGHT.args.specHeader2.name: expected a string or funcref, got 'nil'
[string "=[C]"]: ?
[string "@ACU\Libs\AceConfig-3.0-3\AceConfigRegistry-3.0\AceConfigRegistry-3.0-20.lua"]:50: in function <...-3.0\AceConfigRegistry-3.0\AceConfigRegistry-3.0.lua:45>
[string "@ACU\Libs\AceConfig-3.0-3\AceConfigRegistry-3.0\AceConfigRegistry-3.0-20.lua"]:210: in function <...-3.0\AceConfigRegistry-3.0\AceConfigRegistry-3.0.lua:205>
[string "@ACU\Libs\AceConfig-3.0-3\AceConfigRegistry-3.0\AceConfigRegistry-3.0-20.lua"]:244: in function <...-3.0\AceConfigRegistry-3.0\AceConfigRegistry-3.0.lua:219>
[string "@ACU\Libs\AceConfig-3.0-3\AceConfigRegistry-3.0\AceConfigRegistry-3.0-20.lua"]:254: in function <...-3.0\AceConfigRegistry-3.0\AceConfigRegistry-3.0.lua:219>
[string "@ACU\Libs\AceConfig-3.0-3\AceConfigRegistry-3.0\AceConfigRegistry-3.0-20.lua"]:254: in function <...-3.0\AceConfigRegistry-3.0\AceConfigRegistry-3.0.lua:219>
[string "@ACU\Libs\AceConfig-3.0-3\AceConfigRegistry-3.0\AceConfigRegistry-3.0-20.lua"]:254: in function <...-3.0\AceConfigRegistry-3.0\AceConfigRegistry-3.0.lua:219>
[string "@ACU\Libs\AceConfig-3.0-3\AceConfigRegistry-3.0\AceConfigRegistry-3.0-20.lua"]:254: in function <...-3.0\AceConfigRegistry-3.0\AceConfigRegistry-3.0.lua:219>
[string "@ACU\Libs\AceConfig-3.0-3\AceConfigRegistry-3.0\AceConfigRegistry-3.0-20.lua"]:282: in function `ValidateOptionsTable'
[string "@ACU\Libs\AceConfig-3.0-3\AceConfigRegistry-3.0\AceConfigRegistry-3.0-20.lua"]:324: in function `app'
[string "@Attune\Libs\AceConfig-3.0-3\AceConfigDialog-3.0\AceConfigDialog-3.0-81.lua"]:445: in function `SelectGroup'
[string "@xCT+\core.lua"]:1898: in function `ShowConfigTool'
[string "@xCT+\modules\blizzard.lua"]:60: in function <xCT+\modules\blizzard.lua:57>

Locals:
(*temporary) = "AceConfigRegistry-3.0:ValidateOptionsTable(): xCT+.args.spells.args.classList.args.DEATHKNIGHT.args.specHeader2.name: expected a string or funcref, got 'nil'"

[xCT+.zip](https://github.com/dandruff/xCT/files/6564140/xCT%2B.zip)

**Comment by tylercentral** [comment]
Have you made any progress on this @JFre3 ? Or can you provide some advice on selecting a specific profile to load if my character name has changed so I can copy my settings from retail to this semi-fixed version for tbc? Not having combat text is killing me and I have used xCT exclusively for longer than I can remember, haha.

**Comment by dandruff** [comment]
This might be what you need: https://github.com/Witnesscm/xCT_Classic

**Comment by tylercentral** [comment]
> This might be what you need: https://github.com/Witnesscm/xCT_Classic

Thanks, i searched all over github for forks and somehow missed this, but admittedly i hadn't checked since prepatch (until today when i updated my retail addons) This version also allowed me to straight copy my WTF files from retail into classic BC.  <3

**Comment by RedAces** [comment]
Sorry only retail is supported atm.
