### ISSUE TITLE
xCT not launching in 9.1

### ISSUE THREAD

**Issue by drakunis** [dandruff/xCT#198]
With the drop of 9.1 it seems xCT+ is not launching, using / commands yields the standard "Type '/help' for a listing of a few commands".  Bug sack is showing several lua errors, including the MAELSTROM one that the other user reported:

[maelstrom_error.txt](https://github.com/dandruff/xCT/files/6758642/maelstrom_error.txt)

Here are some other errors if it helps:
[index_defaults_nil_error.txt](https://github.com/dandruff/xCT/files/6758645/index_defaults_nil_error.txt)
[school_mask_physical_error.txt](https://github.com/dandruff/xCT/files/6758646/school_mask_physical_error.txt)

This is the best little combat text addon out there, so I would love to help in any way in getting it back online, just wish I knew more lua so I could help discern what the actual issue is (also have not tried, but planning to, launching the game with all addons disabled and just xCT to see if some of these errors are in conjunction with ElvUI since the xCT text is one that I use in ElvUI).

**Comment by drakunis** [comment]
You know what, I figured it out, the release version is 9.0.2, but there is a beta version released on 6/11/21 that works just fine.

**Comment by Ariandra** [comment]
Where did you find the beta version? xCT+ will load for me but it only displays a black square without any options and the scrolling text is unavailable.
