### ISSUE TITLE
Addon won't load or show up on addon list 

### ISSUE THREAD

**Issue by aayla04** [dandruff/xCT#201]
Hi,

Since the 9.1 launch this addon is not worikng at all. I get no errors or anything similar to that, it just simply does not exist in my addon list (ofc the folder is in the right place).

Would love an update anytime soon, thank you!

**Comment by oBusk** [comment]
Make sure you/your addon client is installing beta versions. Latest version is 4.5.5-Beta2 https://www.curseforge.com/wow/addons/xct-plus/files/3348476

**Comment by dandruff** [comment]
Thank you for the report. New version is out :)
