### ISSUE TITLE
[Bug]: Save Changes button not working

### ISSUE THREAD

**Issue by phaiz** [dandruff/xCT#203]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### WoW version

9.1

### xCT+ version

dandruff-xCT+4.5.5(9.1.0) - Beta 2

### What happened?

When moving the addon frames around, neither the save changes button or the /xct lock command do anything. Hitting the cancel button does work but obviously doesn't save the changes.

**Comment by dandruff** [comment]
Thank you for the report. New version is out and should completely resolve this issue.
