### ISSUE TITLE
[feature]: Should not merge outgoing damage and healing

### ISSUE THREAD

**Issue by oBusk** [dandruff/xCT#206]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature request

Spells like [Consumption](https://www.wowhead.com/spell=274156) uses the same spell ID for both healing and damage, which is unfortunate. The current merging mechanics means that both healing and damage are merged, providing incorrect feedback to the player. 

I think it should be possible to treat merging separately for damage and healing even if it is in the same frame, and that should provide better feedback to the player.

**Comment by RedAces** [comment]
Will be fixed in https://github.com/dandruff/xCT/pull/255
