### ISSUE TITLE
[Bug]: Displaying normal damage as critical

### ISSUE THREAD

**Issue by Lowenfels** [dandruff/xCT#208]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### WoW version

9.1.0.39498

### xCT+ version

4.5.7

### What happened?

Hi, my outgoing not critical damage is displayed the same as outgoing crit damage (with a red star), please help. 
![image](https://user-images.githubusercontent.com/86878173/126860571-4523c198-d71e-4672-b4ea-d7a2431b63e5.png)
![image](https://user-images.githubusercontent.com/86878173/126860720-6be6e35f-13c1-47bb-af0d-1af23d4b67b5.png)

**Comment by dandruff** [comment]
Not to be dismissive, but you are sending your crit damage to your outgoing frame? You could just disable post/pre-fix formatting in misc. But your right it’s not very clear.

**Comment by Lowenfels** [comment]
yes, I send my crit damage to the outgoing frame, I want them to be in one
![image](https://user-images.githubusercontent.com/86878173/126867778-41b83e10-0da9-4075-b637-d1a8951d78c6.png)
these are my prefixes for crit damage, but for some reason they also affect normal damage/
Аnd now when I enable single frame for crit damage, it is not displayed/
Defore the patch everything was ok, everything was in one window and only crit damage was displayed with prefixes

**Comment by dandruff** [comment]
Oh I misunderstood the bug, I’ll take a look at it
