### ISSUE TITLE
[Bug]: bad argument #3 to 'SetFont' (Usage: self:SetFont(fontFile, height, flags))

### ISSUE THREAD

**Issue by Rustyb0y** [dandruff/xCT#215]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### WoW version

10.0.0.46366

### xCT+ version

4.7.0 for WoW 10.0.0

### What happened?

Received a LUA error which I did not expect

### Related Errors

```lua
Interface/SharedXML/FontableFrameMixin.lua:22: bad argument #3 to 'SetFont' (Usage: self:SetFont(fontFile, height, flags))
```

**Comment by dandruff** [comment]
Any more info on when you see this? You can try to create a new profile in xCT+ and see if you still get the Lua error. In order to fix, I might need the saved variables from xCT+

**Comment by Rustyb0y** [comment]
I happens when I log in/reload UI.  I also don't get any actual combat text appearing.

[xCT+lua.txt](https://github.com/dandruff/xCT/files/9917392/xCT%2Blua.txt)

**Comment by Rustyb0y** [comment]
Here is the full error

`6x Interface/SharedXML/FontableFrameMixin.lua:22: bad argument #3 to 'SetFont' (Usage: self:SetFont(fontFile, height, flags))
[string "=[C]"]: in function `SetFont'
[string "@Interface/AddOns/xCT+/modules/frames.lua"]:221: in function `UpdateFrames'
[string "@Interface/AddOns/xCT+/modules/frames.lua"]:109: in function `GetFrame'
[string "@Interface/AddOns/xCT+/modules/frames.lua"]:306: in function `Clear'
[string "@Interface/AddOns/xCT+/modules/combattext.lua"]:906: in function `?'
[string "@Interface/AddOns/xCT+/modules/combattext.lua"]:565: in function <Interface/AddOns/xCT+/modules/combattext.lua:540>

Locals:
 = <function> defined @Interface/SharedXML/FontableFrameMixin.lua:20
 = xCT_PluscriticalFrame {
 0 = <userdata>
 RefreshIfNecessary = <function> defined =[C]:-1
 OnPostShow = <function> defined =[C]:-1
 CalculateLineAlphaValueFromTimestamp = <function> defined =[C]:-1
 GetInsertMode = <function> defined =[C]:-1
 SetTimeVisible = <function> defined =[C]:-1
 GetBackdropColor = <function> defined @Interface/SharedXML/Backdrop.lua:390
 settings = <table> {
 }
 OnFontObjectUpdated = <function> defined =[C]:-1
 frameName = "critical"
 ScrollByAmount = <function> defined =[C]:-1
 GetFading = <function> defined =[C]:-1
 IsTextCopyable = <function> defined =[C]:-1
 Clear = <function> defined =[C]:-1
 shouldFadeAfterInactivity = true
 SetIndentedWordWrap = <function> defined =[C]:-1
 GetTimeVisible = <function> defined =[C]:-1
 MarkLayoutDirty = <function> defined =[C]:-1
 SetFont = <function> defined =[C]:-1
 sizing = xCT_PluscriticalSizingFrame {
 }
 GetMaxLines = <function> defined =[C]:-1
 isLayoutDirty = true
 BackFillMessage = <function> defined =[C]:-1
 hasOwnFontObject = true
 UnpackageEntry = <function> defined =[C]:-1
 FontStringContainer = Frame {
 }
 visibleLines = <table> {
 }
 SetShadowOffset = <function> defined =[C]:-1
 textIsCopyable = false
 SetupPieceVisuals = <function> defined @Interface/SharedXML/Backdrop.lua:246
 GetFont = <function> defined =[C]:-1
 scrollOffset = 0
 SetMaxLines = <function> defined =[C]:-1
 CalculateSelectingCharacterIndicesForVisibleLine = <function> defined =[C]:-1
 PackageEntry = <function> defined =[C]:-1
 fadeDurationSecs = 3
 RefreshDisplay = <function> defined =[C]:-1
 SetFontObject = <function> defined =[C]:-1
 timeVisibleSecs = 10
 MakeFontObjectCustom = <function> defined =[C]:-1
 SetJustifyV = <function> defined =[C]:-1
 SetOnScrollChangedCallback = <function> defined =[C]:-1
 CalculateNumVisibleLines = <function> defined =[C]:-1
 SetBorderBlendMode = <function> defined @Interface/SharedXML/Backdrop.lua:266
 fontObject = table: 0000026FD2C02370 {
 }
 overrideFadeTimestamp = 0
 GetEdgeSize = <function> defined @Interface/SharedXML/Backdrop.lua:188
 SetInsertMode = <function> defined =[C]:-1
 MarkDisplayDirty = <function> defined =[C]:-1
 SetBackdrop = <function> defined @Interface/SharedXML/Backdrop.lua:329
 SetupTextureCoordinates = <function> defined @Interface/SharedXML/Backdrop.lua:214
 HasBackdropInfo = <function> defined @Interface/SharedXML/Backdrop.lua:278
 GetMessageInfo = <function> defined =[C]:-1
 GetOnScrollChangedCallback = <function> defined =[C]:-1
 OnBackdropSizeChanged = <function> defined @Interface/SharedXML/Backdrop.lua:182
 ScrollDown = <function> defined =[C]:-1
 AtTop = <function> defined =[C]:-1
 GetFontObject = <function> defined =[C]:-1
 SetBackdropColor = <function> defined @Interface/SharedXML/Backdrop.lua:399
 SetScrollOffset = <function> defined =[C]:-1
 SetTextCopyable = <function> defined =[C]:-1
 ClearBackdrop = <function> defined @Interface/SharedXML/Backdrop.lua:282
 OnBackdropLoaded = <function> defined @Interface/SharedXML/Backdrop.lua:152
 ApplyBackdrop = <function> defined @Interface/SharedXML/Backdrop.lua:294
 CanEffectivelyFade = <function> defined =[C]:-1
 GetBackdropBorderColor = <function> defined @Interface/SharedXML/Backdrop.lua:409
 SetOnDisplayRefreshedCallback = <function> defined =[C]:-1
 insertMode = 2
 AddMessage = <function> defined =[C]:-1
 OnPreSizeChanged = <function> defined =[C]:-1
 GetScaledCursorPosition = <function> defined =[C]:-1
 OnPostMouseUp = <function> defined =[C]:-1
 ResetSelectingText = <function> defined =[C]:-1
 PageUp = <function> defined =[C]:-1
 SetBackdropBorderColor = <function> defined @Interface/SharedXML/Backdrop.lua:422
 GetNumMessages = <function> defined =[C]:-1
 UpdateSelectingText = <function> defined =[C]:-1
 GetTextColor = <function> defined =[C]:-1
 AtBottom = <function> defined =[C]:-1
 ResetAllFadeTimes = <function> defined =[C]:-1
 ScrollToBottom = <function> defined =[C]:-1
 GetScrollOffset = <function> defined =[C]:-1
 GetSpacing = <function> defined =[C]:-1
 OnPreLoad = <function> def`

**Comment by Cimplex** [comment]
Please update to xCT+ 4.7.1 and let me know if that works!

https://github.com/dandruff/xCT/releases/tag/4.7.1
(On CurseForge soon)

**Comment by Rustyb0y** [comment]
Yes that was it, thanks
