### ISSUE TITLE
[Bug]: xct+ says there is no color named buffsFaded / buffsGained / healingTaken

### ISSUE THREAD

**Issue by bv101rj** [dandruff/xCT#217]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### WoW version

10.0.2.46658

### xCT+ version

4.7.1

### What happened?

After the patch that dropped for the DF launch event xct+ fails to load, and using any thing that would produce a buff (ex: Icebound Fortitude) on your character will instead throw the following into chat:
![image](https://user-images.githubusercontent.com/53923684/202070359-38e032a5-e644-479e-8a59-6d85e686fa2e.png)

Not sure if there anymore debugging I can do on my end to get more useful info. 

### Related Errors

```lua
See the attached image, not getting the normal Lua error popup, could be a client issue.
```

**Comment by bv101rj** [comment]
This is also happening with healing taken it would seem, needed someone to toss heals on me to confirm

**Comment by bv101rj** [comment]
I remembered that bug sack is a thing! 

Find more details below:
`2x Interface/AddOns/xCT+/modules/frames.lua:429: missing color
[string "=[C]"]: in function `error'
[string "@Interface/AddOns/xCT+/modules/frames.lua"]:429: in function `AddMessage'
[string "@Interface/AddOns/xCT+/modules/combattext.lua"]:1716: in function `AuraIncoming'
[string "@Interface/AddOns/xCT+/modules/combattext.lua"]:2004: in function `func'
[string "@Interface/AddOns/xCT+/libs/xCombatParser-1.0-1/xCombatParser-1.0.lua"]:405: in function <...ns/xCT+/libs/xCombatParser-1.0/xCombatParser-1.0.lua:200>

Locals:
(*temporary) = "missing color"`

Another:
`1x Interface/AddOns/xCT+/core.lua:387: attempt to call method 'SetSpellByID' (a nil value)
[string "@Interface/AddOns/xCT+/core.lua"]:387: in function <Interface/AddOns/xCT+/core.lua:382>
[string "@Interface/AddOns/xCT+/core.lua"]:631: in function `UpdateSpamSpells'
[string "@Interface/AddOns/xCT+/core.lua"]:132: in function <Interface/AddOns/xCT+/core.lua:89>
[string "=[C]"]: ?`

I might have some more, I will post them when I find them. Also I forgot to mention it in the description, I think this issue could be related, albeit its closed. 

https://github.com/dandruff/xCT/issues/154

**Comment by Kenoxxxx** [comment]
bump, same thing is happening with me too 
![image](https://user-images.githubusercontent.com/112582682/202081246-fcb2627c-24c4-4607-9ffd-74768836810b.png)

**Comment by Willwarb** [comment]
I have had this issue as well. buffsGained/Faded is the most common.

**Comment by Cimplex** [comment]
Can you try creating a new Profile in the xCT+ options and see if it still happens? I might need to upgrade old settings.

**Comment by bv101rj** [comment]
Absolutely, I can give that a shot tomorrow morning. Before I logged off I don't think I could open the xct options menu. I might also be able to create one manually as well with some tinkering.

**Comment by mamali00072** [comment]
i have this issue too /xct options doesnt open too when you type /xct

**Comment by bv101rj** [comment]
> Absolutely, I can give that a shot tomorrow morning. Before I logged off I don't think I could open the xct options menu. I might also be able to create one manually as well with some tinkering.

Just wanted to confirm that I did attempt to try creating a new profile this morning. However the options menu doesn't come up. 

However, going into WTF and removing the xCT+ lua, does get things working kind of? It places me on the default profile, however it has the same / similar issues:
![image](https://user-images.githubusercontent.com/53923684/202187364-afeafe76-2e6b-444c-ba03-e20aba29eaab.png)

**Comment by bv101rj** [comment]
Moving this issue to complete, most recent release has totally solved my issues. Thanks @Cimplex very much!
