### ISSUE TITLE
Configuration Panel missing from AddOns tab in settings

### ISSUE THREAD

**Issue by sul2001** [dandruff/xCT#218]
Since the Pre-Patch it seems that on the AddOns tab under options that xCT+ no longer shows for me so I am not able to open the configuration panel. I am on version dandruff-xCT+4.7.1(10.0.0)

**Comment by mamali00072** [comment]
i have the same problem after updating + new patch

**Comment by Cimplex** [comment]
Can you use /xct to open the panel? I don't know if I can add it to the new Settings menu (it seem protected, but I might have been doing it wrong)

**Comment by sul2001** [comment]
Sorry I should have mentioned that too, no /xct does not work either. If it helps here is what BugSack is showing.

![image](https://user-images.githubusercontent.com/114005592/202642406-6af2e9df-89cc-4551-b0b9-7132b3618caf.png)
