### ISSUE TITLE
An addition to the spam merger please. Paladin Spell, Resplendent Light

### ISSUE THREAD

**Issue by wilhelmkeidelmeq** [dandruff/xCT#223]
Could we please add the Paladin spell resplendent light to the spam merger. 

https://www.wowhead.com/spell=392903/resplendent-light

Edit:Found two more spells during play which would be nice to have merged, thank you. 

Golden Path: https://www.wowhead.com/spell=377128/golden-path

Seal of Mercy: https://www.wowhead.com/spell=384897/seal-of-mercy?def=107604&rank=2

**Comment by RedAces** [comment]
Merged Seal of Mercy into golden path and added the merge for both other spells in my PR: https://github.com/dandruff/xCT/pull/236/files
