### ISSUE TITLE
Ragefire Spam Merger

### ISSUE THREAD

**Issue by jackwhudson** [dandruff/xCT#232]
Hey!

Great addon. Is it possible to add a custom spell ID to the spell merger list?

Ragefire on DH explodes and shows every explosion. It would be great to see this grouped

**Comment by jackwhudson** [comment]
Bump <3

**Comment by Cimplex** [comment]
Ragefire is 390197, I'll add it in the next version if it's not already there.

**Comment by RedAces** [comment]
Added to my PR.
