### ISSUE TITLE
[Bug]: Repeatedly on Gnarlroot and a few times on Tindril

### ISSUE THREAD

**Issue by Weetbix813** [dandruff/xCT#233]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### WoW version

10.2

### xCT+ version

whatever most current retail

### What happened?

Errors on repeat during Gnarlroot and Tindril, also when use new vigor recharge

### Related Errors

```lua
11x xCT+/modules/combattext.lua:923: bad argument #2 to 'match' (string expected, got nil)
[string "=[C]"]: in function `match'
[string "@xCT+/modules/combattext.lua"]:923: in function `?'
[string "@xCT+/modules/combattext.lua"]:565: in function <xCT+/modules/combattext.lua:540>

Locals:
(*temporary) = ""
(*temporary) = nil
(*temporary) = "string expected, got nil"
```

**Comment by RedAces** [comment]
This came from using "Second wind" which gave you a vigor, correct?
I fixed (???) it in my branch, try it out here: https://github.com/RedAces/xCT/tree/master
PR is open.
