### ISSUE TITLE
LUA errors on DK - GetRuneCooldown

### ISSUE THREAD

**Issue by cheesy-italian** [dandruff/xCT#235]
Ran a dungeon on my DK and was getting spammed with error sounds.  After checking BugSack, this is the LUA error that is the most prevalent:

`28x xCT+/modules/combattext.lua:871: bad argument #1 to 'GetRuneCooldown' (outside of expected range 0 to 4294967295 - Usage: local startTime, duration, isRuneReady = GetRuneCooldown(runeIndex))
[string "=[C]"]: in function `GetRuneCooldown'
[string "@xCT+/modules/combattext.lua"]:871: in function `?'
[string "@xCT+/modules/combattext.lua"]:565: in function <xCT+/modules/combattext.lua:540>

Locals:
(*temporary) = -2099757263
(*temporary) = "outside of expected range 0 to 4294967295 - Usage: local startTime, duration, isRuneReady = GetRuneCooldown(runeIndex)"`

This didn't happen last time I played the toon, which was about 3 weeks ago.  Not sure if there is something else going on that might be conflicting with this but I have been using xCT+ for a little while now and this if the first time this has happened.
![Wow_wgAzp1W7Nc](https://github.com/dandruff/xCT/assets/22350545/b5a2452c-3b01-4b32-bae2-28c2219a454d)

**Comment by RedAces** [comment]
(Hopefully) fixed on my version: https://github.com/RedAces/xCT/tree/master
Ive created a PR.

**Comment by Cimplex** [comment]
Looks good, thank you @RedAces, I'll hopefully make a new version this weekend.
