### ISSUE TITLE
[feature]: Custom Additions to Spam Merger

### ISSUE THREAD

**Issue by Retjesir** [dandruff/xCT#241]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature request

It would be really awesome if we had more customization options within the Spam Merger.

The main two features would be adding our own Spells by SpellID and secondarily being able to update the Interval Merge Duration. 
![Screenshot 2024-05-18 214844](https://github.com/dandruff/xCT/assets/170218606/46ba1bdf-d057-40d6-a08b-f93b62032aeb)

**Comment by Cimplex** [comment]
I would love to be able to add this.

For now, you can edit this file: [config/merge_class.lua](https://github.com/dandruff/xCT/blob/master/config/merge_class.lua)

It is pretty well commented. Some things to point out:

Look for the Class and then Spec (This is for organization in the UI only, they all get mixed together in the end).

```lua
    spell '405345' '2.0'  --  Talent: Wake of Ashes
    alias '255937' '405345'  --  Talent: Wake of Ashes
    alias '405350' '405345'  --  Talent: Wake of Ashes
```

On the first line, the 'spell' keyword signifies that this is the main entry. The '405345' is the spell ID it will look for in the combat log (it will also use that icon). The second number is in seconds, how long to wait and collect more events before totalling and displaying the result.

The second two lines are useful for when an ability has multiple different types of damage. The alias keyword signifies that when the first number '255937' is found in the combat log, change it to the second number '405345' and use that to merge.
