### ISSUE TITLE
[Bug]: TWW was released, please release the TWW version of xCT

### ISSUE THREAD

**Issue by RedAces** [dandruff/xCT#244]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### WoW version

11.0

### xCT+ version

4.8.0

### What happened?

Please re-release the TWW version of xCT, because 11.0 prepatch just dropped.
Thank you!

**Comment by clancyby** [comment]
in 11.02 full broken

**Comment by Cimplex** [comment]
CurseForge has the beta that should support The War Within, but the TOC is out dated (so you will have to load out dated addons). I'll merge the new TOC now
