### ISSUE TITLE
Incoming Damage seems to be ignoring settings?

### ISSUE THREAD

**Issue by diazanite** [dandruff/xCT#248]
I noticed around either around the start of prepatch or when they actually merged the launch version of TWW with prepatch that the incoming damage panel specifically has either completely changed itself without changing settings, or is ignoring settings as a whole, and seems to merge many separate hits into <event>x<numberofhits> without having the setting turned on.

here's a picture of what my panels looked like [before](https://imgur.com/71Dgl8u) whenever this started occurring, vs [today](https://imgur.com/tkztypy) where for whatever reason absorbed hits, dodges, misses, etc are acting normally, but both melee and magic schools arent displaying properly. i dont think the addon itself has thrown any error messages for something like swatter to catch, and i havent changed any settings in quite a long time.

**Comment by diazanite** [comment]
update; it seems to be spam merger related. turning it off returned both the icon and name to incoming damage events

**Comment by RedAces** [comment]
Should be fixed in 4.8.4!
