### ISSUE TITLE
Damage events appear considerably delayed when compared with other combat text methods/addons

### ISSUE THREAD

**Issue by Laxxzz** [dandruff/xCT#253]
I love xCT, it's honestly a godsend with respect to MSBT seemily having kicked the bucket finally. My only issue is that it seems that damage event's aren't displayed in any of the fields for almost 2 seconds or so - I can't seem to find a setting or area in the settings that would cause this. 

Is this intended? Known issue? Something I've done?

Thanks for you time, looking forward to your reply.

**Comment by Laxxzz** [comment]
Figured this out, it's the spam merger that's adding this delay - turning it off and just filtering out what I don't want shown did the trick.

**Comment by RedAces** [comment]
Can you try the cleanup branch? Ive done a lot of things in it and it should be massivly better.

**Comment by RedAces** [comment]
You can use the 4.9.0-alpha2 for this test.

**Comment by Laxxzz** [comment]
Hey there man, sorry for getting back to you so late - ill do just this and
let you know the result.
