### ISSUE TITLE
[Bug]: Merger settings page does not have Merge Incoming Damage

### ISSUE THREAD

**Issue by Robeok** [dandruff/xCT#254]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### WoW version

11.05.57534

### xCT+ version

4.8.3

### What happened?

Income Damage will be merged when the Merger is enabled. It cannot be closed alone.

**Comment by RedAces** [comment]
Will be in 4.9.0. You can test 4.9.0-alpha4!
