### ISSUE TITLE
Option: Hide Criticals Issues

### ISSUE THREAD

**Issue by behub** [dandruff/xCT#69]
Since the recent commit that added support for 'Hide Criticals' during moments in a fight i get spammed with this ..

![Chat Window Errors](http://puu.sh/k2E9I/62fcb9a8ef.jpg)

I have the 'Outgoing Critical' set to forward events to the 'Outgoing' frame.

**Comment by Cimplex** [comment]
Ew, I will figure that out

**Comment by behub** [comment]
Doesn't seem to occur on my Paladin. That log was from my Monk.

**Comment by behub** [comment]
Did some tinkering ..

I replaced the 'frame' variable with the 'message in frames.lua at line 332

![Debug Spell ID](http://puu.sh/k55aa/35264e3e3b.jpg)

Stagger is causing it to appear.
