### ISSUE TITLE
string.sub function returns unvalid value on non-English client

### ISSUE THREAD

**Issue by WetU** [dandruff/xCT#71]
modules\combattext.lua : 499 ~ 501 lines are using string.sub function.

non-English client (I'm playing koKR client) display unvalid string.

for example, global string ACTION_SPELL_STOLEN is "훔침' in Korean.

but displayed string is "??침"

**Comment by Cimplex** [comment]
I wonder if it is actually the "string.upper" D:

Can you try this command in your chat:
```
    /dump string.upper(ACTION_SPELL_STOLEN)
```

I suspect it will just return question marks.

**Comment by WetU** [comment]
Dump: value=string.upper(ACTION_SPELL_STOLEN)
[1]="훔침"

also, string.lower returns equal value

**Comment by WetU** [comment]
Dump: value=string.upper(string.sub(ACTION_SPELL_STOLEN, 1, 1))
[1]=""

Dump: value=string.sub(ACTION_SPELL_STOLEN, 1, 1)
[1]="?"

This is because the Unicode UTF-8

http://www.wowace.com/addons/utf8/

I found helpful library addon that maybe solve this problem.

**Comment by Cimplex** [comment]
Hopefully this fixes your issue. It will be included in 4.1.7 88a4b87bb841e150e8d92ccae1dea7a987ef622a

**Comment by WetU** [comment]
It displayed correctly in new version

Thanks!
