### ISSUE TITLE
Merge issue, enhancement shaman, Flametongue attack

### ISSUE THREAD

**Issue by Firewall** [dandruff/xCT#84]
Flametongue doesnt seem to be merging correctly 😃 
http://www.wowhead.com/spell=10444/flametongue-attack

![](https://i.imgur.com/6YmVfZO.png)

**Comment by behub** [comment]
I'm looking into this now. By the time you read this i would of most likely done a pull request for it :)

**Comment by behub** [comment]
I've done it as 1.5 seconds but it may get a bit spammy still. If you find it's just flooding the scrolling text then let me know. I must of missed it when i was going through every class.

**Comment by behub** [comment]
Though you need to wait for dandruff to actually merge it in.
