### ISSUE TITLE
Dispel is delayed

### ISSUE THREAD

**Issue by Homaxz** [dandruff/xCT#93]
Using 4.3.0-beta 5, in the "General" frame, I like to show what I dispel / purge off enemies. 
This message shows a few seconds after successfully purging  / dispelling something.

Using 4.2.3, the message shows instantly (which is what I want).
From my testing, only dispelling and purging are delayed, all the other options in the "General" Frame are still displaying instantly.

I hope you can restore this back to how it was in 4.2.3.

**Comment by Cimplex** [comment]
Sorry, this is probably a combination of you changing a setting in >4.3.0 and it getting erased by the profile resets.

I am going to change the default value in the next version, but if you don't want to wait (really no reason to wait), go to the merge settings and disable Dispel Merges.

**Comment by Homaxz** [comment]
Yes this worked. Thanks for the quick response!
