### ISSUE TITLE
No Maelstrom gain setting for class power

### ISSUE THREAD

**Issue by scathee** [dandruff/xCT#97]
Class power shows gains for other classes such as Eclipse, Runes, Mana, Holy Power, etc. But there is nothing for Maelstrom. It's very important for shamans to manage their maelstrom and having CT for it would be really helpful. Other addons (SCT in particular) can already do this. Thank you.

**Comment by Cimplex** [comment]
Found the issue, will update with fix!

**Comment by Cimplex** [comment]
Should be fixed now. Thanks for the report!
