### ISSUE TITLE
Failed parsing CHAT_MSG_LOOT event

### ISSUE THREAD

**Issue by WetU** [dandruff/xCT#99]
1x xCT+\modules\combattext.lua:1278: bad argument #2 to 'strsplit' (string expected, got nil)
[C]: in function `strsplit'
xCT+\modules\combattext.lua:1278: in function`?'
xCT+\modules\combattext.lua:539: in function <xCT+\modules\combattext.lua:523>

Locals:
(_temporary) = ":"
(_temporary) = nil
(*temporary) = "string expected, got nil"

CHAT_MSG_LOOT event's message is "|cffffffff|Hitem:119299::::::::100:252::::::|h[드레노어 기계공학의 비밀]|h|r을 만들었습니다."

This message appeared when make a craft item.

**Comment by Cimplex** [comment]
I see the issue, but I need to get my hands on the GlobalStrings.lua file in Korean.
